package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// ContainerSecuritySpec defines the desired state of ContainerSecurity
type ContainerSecuritySpec struct {
	// Selector is a label selector used to identify which deployments/statefulsets to secure
	Selector metav1.LabelSelector `json:"selector"`

	// ScanInterval is how often to scan and update the containers (in hours)
	// +kubebuilder:validation:Minimum=1
	// +kubebuilder:validation:Maximum=168
	ScanInterval int `json:"scanInterval"`

	// AutoPatch determines whether to automatically apply security patches
	AutoPatch bool `json:"autoPatch"`

	// ImagePushSecret is the name of the secret containing credentials for pushing updated images
	ImagePushSecret string `json:"imagePushSecret,omitempty"`

	// TagSuffix is the suffix to append to secured container images (default: "-sc")
	TagSuffix string `json:"tagSuffix,omitempty"`
}

// DeepCopyInto is an autogenerated deepcopy function
func (in *ContainerSecuritySpec) DeepCopyInto(out *ContainerSecuritySpec) {
	*out = *in
	in.Selector.DeepCopyInto(&out.Selector)
}

// DeepCopy is an autogenerated deepcopy function
func (in *ContainerSecuritySpec) DeepCopy() *ContainerSecuritySpec {
	if in == nil {
		return nil
	}
	out := new(ContainerSecuritySpec)
	in.DeepCopyInto(out)
	return out
}

// ContainerSecurityStatus defines the observed state of ContainerSecurity
type ContainerSecurityStatus struct {
	// LastScanTime is when the last security scan was performed
	LastScanTime *metav1.Time `json:"lastScanTime,omitempty"`

	// LastUpdateTime is when the last security update was applied
	LastUpdateTime *metav1.Time `json:"lastUpdateTime,omitempty"`

	// Conditions represents the latest available observations of the security state
	Conditions []metav1.Condition `json:"conditions,omitempty"`
}

// DeepCopyInto is an autogenerated deepcopy function
func (in *ContainerSecurityStatus) DeepCopyInto(out *ContainerSecurityStatus) {
	*out = *in
	if in.LastScanTime != nil {
		in, out := &in.LastScanTime, &out.LastScanTime
		*out = (*in).DeepCopy()
	}
	if in.LastUpdateTime != nil {
		in, out := &in.LastUpdateTime, &out.LastUpdateTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function
func (in *ContainerSecurityStatus) DeepCopy() *ContainerSecurityStatus {
	if in == nil {
		return nil
	}
	out := new(ContainerSecurityStatus)
	in.DeepCopyInto(out)
	return out
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Last Scan",type="date",JSONPath=".status.lastScanTime"
// +kubebuilder:printcolumn:name="Last Update",type="date",JSONPath=".status.lastUpdateTime"

// ContainerSecurity is the Schema for the containersecurities API
type ContainerSecurity struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   ContainerSecuritySpec   `json:"spec,omitempty"`
	Status ContainerSecurityStatus `json:"status,omitempty"`
}

// DeepCopyInto is an autogenerated deepcopy function
func (in *ContainerSecurity) DeepCopyInto(out *ContainerSecurity) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function
func (in *ContainerSecurity) DeepCopy() *ContainerSecurity {
	if in == nil {
		return nil
	}
	out := new(ContainerSecurity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function
func (in *ContainerSecurity) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// +kubebuilder:object:root=true

// ContainerSecurityList contains a list of ContainerSecurity
type ContainerSecurityList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ContainerSecurity `json:"items"`
}

// DeepCopyInto is an autogenerated deepcopy function
func (in *ContainerSecurityList) DeepCopyInto(out *ContainerSecurityList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ContainerSecurity, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function
func (in *ContainerSecurityList) DeepCopy() *ContainerSecurityList {
	if in == nil {
		return nil
	}
	out := new(ContainerSecurityList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function
func (in *ContainerSecurityList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func init() {
	SchemeBuilder.Register(&ContainerSecurity{}, &ContainerSecurityList{})
}
